environment: prd
arch: arm64
ingress:
  domain: bcs.svc.fsociety


secrets:
  qdrantReadWriteApiKey: '${QDRANT_READ_WRITE_API_KEY}'
  qdrantReadOnlyApiKey: '${QDRANT_READ_ONLY_API_KEY}'
  mongodbPassword: '${MONGODB_PASSWORD}'
  geminiApiKey: '${GEMINI_API_KEY}'