environment: null

arch: amd64

oidc:
  jwksUri: https://dev-kpiuw0wghy7ta8x8.us.auth0.com/.well-known/jwks.json
  issuer: https://dev-kpiuw0wghy7ta8x8.us.auth0.com/
  audience: https://bcs-api/
  clientId: ZB6G0jz2KVW6acAmLhdibQ5ykL02YcBy
  scopes: 'openid profile email offline_access api:use'

ui:
  resources: {}


api:
  resources: {}

ingress:
  domain: null
  extraAnnotations:
    nginx.ingress.kubernetes.io/limit-rps: "20"                      # 10 requests per second
    nginx.ingress.kubernetes.io/limit-burst: "40"                    # optional: allows short bursts
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "1"
    nginx.ingress.kubernetes.io/limit-rate-after: "0"                # apply immediately

qdrant:
  enabled: true
  config:
    cluster:
      enabled: false
      p2p:
        port: 6335
        enable_tls: false
      consensus:
        tick_period_ms: 100
  resources: {}
  persistence:
    size: 5Gi
  apiKey:
    valueFrom:
      secretKeyRef:
        name: bcs
        key: apiKeyReadWrite
  readOnlyApiKey:
    valueFrom:
      secretKeyRef:
        name: bcs
        key: apiKeyReadOnly

mongodb:
  enabled: true
  port: '27017'
  username: bcs
  resources: {}
  storage:
    volumeName: "mongodb-volume"
    requestedSize: 5Gi
    accessModes:
      - ReadWriteOnce
  env:
    - name: MONGO_INITDB_ROOT_USERNAME
      value: root
    - name: MONGO_INITDB_DATABASE
      value: bcs
    - name: USERDB_USER
      value: bcs
    - name: MONGO_INITDB_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: bcs
          key: mongodbPassword
    - name: USERDB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: bcs
          key: mongodbPassword
secrets:
  qdrantReadWriteApiKey: null
  qdrantReadOnlyApiKey: null
  mongodbPassword: null
  geminiApiKey: null