name: Manual Deploy Version

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the deployment environment"
        required: true
        type: choice
        options:
          - stg
          - uat
          - prd

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy.yaml
    with:
      env: ${{ inputs.environment }}
      version: ${{ github.ref_name }}
      uninstall: false
    secrets: inherit